Stripe integration
keymanapp/donate.keyman.com pull request #8
Opened 2019-04-12 20:23 UTC by SeriousMatt

2019-04-12 20:34 UTC, SeriousMatt commented
Hi @mcdurdin, sorry for the gibberish commit messages...most of these were tests to force deployments in some of the test environments. The end result is both applications are deployed to wwwroot in a front and back folder with each application running. This is also assuming the configuration variables are set correctly (see image)![image](https://user-images.githubusercontent.com/12531332/56064602-83151d80-5d40-11e9-9cce-d278a82790ad.png). This will probably require a fresh clean workspace (as was last time) in order for it to work correctly.

2019-04-12 20:38 UTC, SeriousMatt commented
Also, this will be deployed with the test keys. Here is my own [test environment] I have been using (https://finalkeyman.azurewebsites.net/app.view.html)  Assuming this is good to go we can switch them over to live ones.

2019-04-13 08:00 UTC, mcdurdin requested changes
There should not be keys referenced in the source code.

Can you let me know what the values should be for the environment variables you want set?
`sk_test`
`virtualDirPath`
`WEBSITE_NODE_DEFAULT_VERSION`

2019-04-13 08:00 UTC, mcdurdin commented on src/app/app.component.ts
> +    let stripe_key = 'pk_test_eM74cMSAfGXWvrLZnz7gCXuA';
Is this another leaked key?

2019-04-13 12:39 UTC, SeriousMatt commented on src/app/app.component.ts
> +    let stripe_key = 'pk_test_eM74cMSAfGXWvrLZnz7gCXuA';
The name of that key is Publishable key. [More here](. https://stackoverflow.com/questions/38819887/whats-the-purpose-of-the-secret-key-for-stripe-also-is-this-safe)

2019-04-13 12:48 UTC, SeriousMatt commented on src/app/app.component.ts
> +    let stripe_key = 'pk_test_eM74cMSAfGXWvrLZnz7gCXuA';
Agreed. I've already set them up in the Application settings section. You should be able to view them there. When we are ready to switch over the environment to live we can then update the values.

2019-04-13 23:59 UTC, mcdurdin approved these changes

2019-04-14 02:22 UTC, merged